- hosts: all
  become: yes
  tasks:
    - name: Update APT package manager repositories cache
      become: true
      apt:
        update_cache: yes
    - name: ensure vim is at the latest version
      apt: name=vim state=latest
    - name: install zip
      apt: name=zip state=latest
